# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9,3.10,3.11] # You can build against multiple Python versions.


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }} # Name of an action that sets up Python.
        uses: actions/setup-python@v2 # A pre-built GitHub Action that sets up a Python environment.
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies # The first step that isn't just calling another action.
        run: |
          python -m pip install --upgrade pip # Upgrade pip to the latest version.
          pip install pytest flake8 pylint # Install pytest flake8 pylint.
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi # If we have a requirements.txt, then install it.
  
          
      - name: Run pylint
        run: |
          pylint your_module_or_package

      - name: Run pytest and flake8
        run: |
          pytest
          flake8 your_module_or_package
